version: '3.9'

volumes:
  pgdata:
  postgres_data:
  static_volume:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
            /bin/sh -c  "
            python manage.py collectstatic --no-input && python manage.py migrate
            && gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/src/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:  
      - 8001:80
    depends_on:
      - backend

  pgadmin:
    container_name: pgadmin_co
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "7070:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    